Debug = false
Format = false
RPCServer = "47.93.20.102:1236"
RPCUser = "admin"
RPCPassword = "123"
RPCCert = ""
NoTLS = true
TLSSkipVerify = true
Proxy = ""
ProxyUser = ""
ProxyPass = ""
Timeout = "30s"
